package expo.modules.callkit

// ChatMessagingStyleHandler — renders chat_message + chat_reaction pushes
// using NotificationCompat.MessagingStyle (WhatsApp / Telegram style), with
// inline reply via RemoteInput + smart-reply chips + mute-from-notification.
// Called from CallFirebaseMessagingService before falling back to the Expo
// delegate. If this returns false, the caller forwards to Expo normally.
//
// 2026-05-17 — gap_notifications P0+P1 implementation.

import android.app.Notification
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.util.Log
import androidx.core.app.NotificationCompat
import androidx.core.app.Person
import androidx.core.app.RemoteInput
import androidx.core.graphics.drawable.IconCompat
import com.google.firebase.messaging.RemoteMessage
import java.net.HttpURLConnection
import java.net.URL
import org.json.JSONArray

object ChatMessagingStyleHandler {

    private const val TAG = "ChatMsgStyleHandler"
    private const val PREFS = "chatyy_chat_threads"
    private const val MAX_MESSAGES_PER_THREAD = 8

    // RemoteInput keys + intent actions — kept in lockstep with the JS side
    // (see services/pushNotifications.js, response listener).
    const val KEY_REPLY_TEXT = "key_chat_reply_text"
    const val ACTION_QUICK_REPLY = "com.onemundo.mail.ACTION_CHAT_REPLY"
    const val ACTION_MARK_READ = "com.onemundo.mail.ACTION_CHAT_MARK_READ"
    const val ACTION_MUTE_8H = "com.onemundo.mail.ACTION_CHAT_MUTE_8H"
    const val ACTION_SNOOZE_1H = "com.onemundo.mail.ACTION_CHAT_SNOOZE_1H"
    const val ACTION_SMART_REPLY = "com.onemundo.mail.ACTION_CHAT_SMART_REPLY"

    /**
     * Try to handle the FCM message as a chat message rendered with
     * MessagingStyle. Returns true if we displayed our own notification (and
     * the caller should NOT forward to Expo), false otherwise.
     */
    fun tryHandle(ctx: Context, message: RemoteMessage): Boolean {
        val data = message.data
        val type = data["type"] ?: return false
        if (type != "chat_message" && type != "chat_mention" && type != "chat_reaction") return false

        // Silent / snoozed pushes: backend sets `_silent: "1"` when user is in
        // global snooze. We still hydrate the thread so the message list is
        // up to date on next open, but skip notification display.
        val isSilent = data["_silent"] == "1"

        try {
            val conversationId = data["conversation_id"] ?: return false
            val senderEmail = data["sender_email"] ?: data["reactor_email"] ?: ""
            val senderName = pickSenderName(data, senderEmail)
            val body = if (type == "chat_reaction") {
                (data["emoji"] ?: "❤️") + " " + (message.notification?.body ?: data["body"] ?: "")
            } else {
                message.notification?.body ?: data["body"] ?: ""
            }
            val avatarUrl = data["sender_avatar"] ?: data["image"] ?: ""
            val isGroup = (data["thread_id"] ?: "").startsWith("chat_") && data.containsKey("group_name")
            val convName = data["group_name"] ?: senderName
            val isKeywordHit = data["keyword_match"] == "1"

            // Avatar bitmap (best-effort, 1s timeout). Falls back to a
            // monochrome circle generated by NotificationCompat when null.
            val avatarBitmap: Bitmap? = if (avatarUrl.isNotEmpty()) downloadBitmap(avatarUrl) else null
            val senderPerson = Person.Builder()
                .setName(senderName)
                .setKey(senderEmail.ifEmpty { senderName })
                .apply { if (avatarBitmap != null) setIcon(IconCompat.createWithBitmap(avatarBitmap)) }
                .build()

            // Persist this message into the thread so subsequent pushes for
            // the same conversation render as a stack (WhatsApp pattern).
            val now = System.currentTimeMillis()
            appendMessageToThread(ctx, conversationId, senderName, body, now)

            // Channel: chat (or chat_keyword if user matched a keyword and
            // wanted a distinct sound). Both are pre-created in JS via
            // expo-notifications setNotificationChannelAsync.
            val channelId = if (isKeywordHit) "chat_keyword" else "chat"

            // Build MessagingStyle from the thread cache.
            val mePerson = Person.Builder()
                .setName("Você")
                .setKey("me")
                .build()
            val style = NotificationCompat.MessagingStyle(mePerson)
                .setGroupConversation(isGroup)
            if (isGroup) style.conversationTitle = convName
            for (m in loadThread(ctx, conversationId)) {
                val p = Person.Builder()
                    .setName(m.senderName)
                    .setKey(m.senderName)
                    .apply { if (avatarBitmap != null && m.senderName == senderName) setIcon(IconCompat.createWithBitmap(avatarBitmap)) }
                    .build()
                style.addMessage(m.text, m.timestamp, p)
            }

            val notifId = (conversationId.hashCode() and 0x7FFFFFFF)

            // RemoteInput for inline quick reply (typed message)
            val remoteInput = RemoteInput.Builder(KEY_REPLY_TEXT)
                .setLabel("Mensagem...")
                .build()

            val replyIntent = Intent(ACTION_QUICK_REPLY).apply {
                setPackage(ctx.packageName)
                putExtra("conversation_id", conversationId)
                putExtra("notif_id", notifId)
            }
            val replyPendingIntent = PendingIntent.getBroadcast(
                ctx,
                notifId,
                replyIntent,
                pendingIntentFlags(mutable = true)
            )
            val replyAction = NotificationCompat.Action.Builder(
                android.R.drawable.ic_menu_send,
                "Responder",
                replyPendingIntent
            )
                .addRemoteInput(remoteInput)
                .setSemanticAction(NotificationCompat.Action.SEMANTIC_ACTION_REPLY)
                .setAllowGeneratedReplies(true)
                .build()

            // Mark-as-read action
            val markReadIntent = Intent(ACTION_MARK_READ).apply {
                setPackage(ctx.packageName)
                putExtra("conversation_id", conversationId)
                putExtra("notif_id", notifId)
            }
            val markReadPI = PendingIntent.getBroadcast(
                ctx,
                notifId + 1,
                markReadIntent,
                pendingIntentFlags(mutable = false)
            )
            val markReadAction = NotificationCompat.Action.Builder(
                android.R.drawable.ic_menu_view,
                "Marcar como lido",
                markReadPI
            )
                .setSemanticAction(NotificationCompat.Action.SEMANTIC_ACTION_MARK_AS_READ)
                .build()

            // Mute 8h action
            val muteIntent = Intent(ACTION_MUTE_8H).apply {
                setPackage(ctx.packageName)
                putExtra("conversation_id", conversationId)
                putExtra("notif_id", notifId)
            }
            val mutePI = PendingIntent.getBroadcast(
                ctx,
                notifId + 2,
                muteIntent,
                pendingIntentFlags(mutable = false)
            )
            val muteAction = NotificationCompat.Action.Builder(
                android.R.drawable.ic_lock_silent_mode,
                "Silenciar 8h",
                mutePI
            ).build()

            // Snooze 1h action — silent push reroute for an hour
            val snoozeIntent = Intent(ACTION_SNOOZE_1H).apply {
                setPackage(ctx.packageName)
                putExtra("notif_id", notifId)
            }
            val snoozePI = PendingIntent.getBroadcast(
                ctx,
                notifId + 3,
                snoozeIntent,
                pendingIntentFlags(mutable = false)
            )
            val snoozeAction = NotificationCompat.Action.Builder(
                android.R.drawable.ic_menu_recent_history,
                "Soneca 1h",
                snoozePI
            ).build()

            // Tap intent — open the chat conversation
            val openIntent = ctx.packageManager.getLaunchIntentForPackage(ctx.packageName)?.apply {
                putExtra("conversation_id", conversationId)
                putExtra("sender_email", senderEmail)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP)
            }
            val openPI = openIntent?.let {
                PendingIntent.getActivity(ctx, notifId + 100, it, pendingIntentFlags(mutable = false))
            }

            val builder = NotificationCompat.Builder(ctx, channelId)
                .setSmallIcon(android.R.drawable.ic_dialog_email)
                .setStyle(style)
                .setShortcutId("chat_$conversationId")
                .setLocusId(androidx.core.content.LocusIdCompat("chat_$conversationId"))
                .setAutoCancel(true)
                .setOnlyAlertOnce(false)
                .setCategory(NotificationCompat.CATEGORY_MESSAGE)
                .setGroup("chat_$conversationId")
                .setPriority(if (isKeywordHit) NotificationCompat.PRIORITY_MAX else NotificationCompat.PRIORITY_HIGH)
                .addAction(replyAction)
                .addAction(markReadAction)
                .addAction(muteAction)
                .addAction(snoozeAction)
            if (openPI != null) builder.setContentIntent(openPI)
            if (avatarBitmap != null) builder.setLargeIcon(avatarBitmap)

            // [notif-p0p1] Smart reply chips in the bubble above the keyboard.
            // Wear OS auto-pulls these via the same RemoteInput once a single
            // choice list is attached — no extra wiring needed.
            val smartReplies = parseSmartReplies(data["smart_replies"])
            if (smartReplies.isNotEmpty()) {
                val choices = smartReplies.toTypedArray<CharSequence>()
                val srRemoteInput = RemoteInput.Builder(KEY_REPLY_TEXT)
                    .setLabel("Sugestões")
                    .setChoices(choices)
                    .build()
                // Replace the existing reply action's RemoteInput so the
                // choices appear as one-tap chips. Android merges them with
                // the typed input.
                builder.clearActions()
                val replyWithChoices = NotificationCompat.Action.Builder(
                    android.R.drawable.ic_menu_send,
                    "Responder",
                    replyPendingIntent
                )
                    .addRemoteInput(srRemoteInput)
                    .setSemanticAction(NotificationCompat.Action.SEMANTIC_ACTION_REPLY)
                    .setAllowGeneratedReplies(true)
                    .build()
                builder.addAction(replyWithChoices)
                builder.addAction(markReadAction)
                builder.addAction(muteAction)
                builder.addAction(snoozeAction)
            }

            if (isSilent) {
                // Persisted the thread, but don't display. Caller still
                // returns true so we don't double-render via Expo.
                Log.d(TAG, "Silent push (snoozed) — thread updated, no display")
                return true
            }

            val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            nm.notify(notifId, builder.build())
            Log.d(TAG, "Posted MessagingStyle notification for conv=$conversationId notifId=$notifId smartReplies=${smartReplies.size}")
            return true
        } catch (t: Throwable) {
            Log.w(TAG, "tryHandle failed — falling back to Expo delegate: ${t.message}", t)
            return false
        }
    }

    private fun pickSenderName(data: Map<String, String>, email: String): String {
        val raw = data["sender_name"]?.takeIf { it.isNotBlank() }
            ?: email.substringBefore('@').takeIf { it.isNotBlank() }
            ?: "Contato"
        // Cap to keep MessagingStyle title clean
        return raw.take(40)
    }

    private fun parseSmartReplies(raw: String?): List<String> {
        if (raw.isNullOrBlank()) return emptyList()
        return try {
            // FCM stringifies arrays — backend ships JSON. Decode here.
            val arr = JSONArray(raw)
            val out = mutableListOf<String>()
            for (i in 0 until arr.length().coerceAtMost(3)) {
                val s = arr.optString(i, "").trim().take(40)
                if (s.isNotEmpty()) out.add(s)
            }
            out
        } catch (t: Throwable) {
            // If backend sent comma-separated, try that fallback
            raw.split(",", "|").map { it.trim().take(40) }.filter { it.isNotEmpty() }.take(3)
        }
    }

    // ---- thread cache (SharedPreferences-backed) -----------------------------

    private data class ThreadMsg(val senderName: String, val text: String, val timestamp: Long)

    private fun appendMessageToThread(ctx: Context, conversationId: String, sender: String, text: String, ts: Long) {
        try {
            val sp = ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            val key = "thread_$conversationId"
            val existing = sp.getString(key, "") ?: ""
            val arr = if (existing.isEmpty()) JSONArray() else try { JSONArray(existing) } catch (_: Throwable) { JSONArray() }
            arr.put(JSONArray().put(sender).put(text).put(ts))
            // Trim oldest to cap
            val trimmed = if (arr.length() > MAX_MESSAGES_PER_THREAD) {
                val keep = JSONArray()
                val start = arr.length() - MAX_MESSAGES_PER_THREAD
                for (i in start until arr.length()) keep.put(arr.get(i))
                keep
            } else arr
            sp.edit().putString(key, trimmed.toString()).apply()
        } catch (t: Throwable) {
            Log.w(TAG, "appendMessageToThread failed: ${t.message}")
        }
    }

    private fun loadThread(ctx: Context, conversationId: String): List<ThreadMsg> {
        return try {
            val sp = ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            val raw = sp.getString("thread_$conversationId", "") ?: ""
            if (raw.isEmpty()) return emptyList()
            val arr = JSONArray(raw)
            val out = mutableListOf<ThreadMsg>()
            for (i in 0 until arr.length()) {
                val item = arr.optJSONArray(i) ?: continue
                out.add(ThreadMsg(item.optString(0), item.optString(1), item.optLong(2)))
            }
            out
        } catch (t: Throwable) {
            emptyList()
        }
    }

    /** Public: drop the thread cache when user marks the chat read. */
    fun clearThread(ctx: Context, conversationId: String) {
        ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit().remove("thread_$conversationId").apply()
    }

    // ---- bitmap downloader (synchronous, 1s timeout) ------------------------

    private fun downloadBitmap(url: String): Bitmap? {
        return try {
            val parsed = URL(if (url.startsWith("http")) url else "https://chatyy.com.br$url")
            val conn = parsed.openConnection() as HttpURLConnection
            conn.connectTimeout = 1000
            conn.readTimeout = 1500
            conn.doInput = true
            conn.connect()
            val bm = BitmapFactory.decodeStream(conn.inputStream)
            conn.disconnect()
            bm
        } catch (t: Throwable) {
            Log.w(TAG, "downloadBitmap failed for $url: ${t.message}")
            null
        }
    }

    private fun pendingIntentFlags(mutable: Boolean): Int {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            PendingIntent.FLAG_UPDATE_CURRENT or (if (mutable) PendingIntent.FLAG_MUTABLE else PendingIntent.FLAG_IMMUTABLE)
        } else {
            PendingIntent.FLAG_UPDATE_CURRENT
        }
    }
}
