// UploadLiveActivity.swift — [2026-10-09 live-activity] Live Activity /
// Dynamic Island for a LARGE chat media upload ("Enviando vídeo · 42%").
//
// App-side half. The UI lives in the SAME WidgetKit extension as the call
// Live Activity (ChatyyCallActivity, generated by plugins/with-live-activity.js)
// — no extra bundle id / provisioning profile beyond the one the call
// activity already needs (scripts/asc-create-liveactivity-profile.js).
//
// Driven natively by ChatTransferManager (background URLSession), so progress
// keeps flowing while JS is paused and the activity is ended even when the
// upload completes after a background relaunch.
//
// Gated exactly like CallLiveActivity: a runtime no-op unless the app's
// Info.plist has NSSupportsLiveActivities=true (plugin ON, CHATYY_LIVE_ACTIVITY=1)
// and the user allows Live Activities. ActivityKit is weak-linked
// (expo-background-upload.podspec) and every use is @available-gated.
//
// KEEP IN SYNC: `ChatyyUploadAttributes` must match the copy embedded in
// plugins/with-live-activity.js field-for-field (ActivityKit decodes it in the
// extension process by type name).

import Foundation
import ActivityKit

@available(iOS 16.1, *)
struct ChatyyUploadAttributes: ActivityAttributes {
  public struct ContentState: Codable, Hashable {
    /// 0…1
    var progress: Double
    /// "uploading" | "done" | "failed"
    var status: String
  }
  var transferId: String
  /// "video" | "photo" | "audio" | "file"
  var kind: String
  /// Localized, e.g. "Enviando vídeo"
  var title: String
  var doneLabel: String
  var failedLabel: String
  /// e.g. "48 MB"
  var sizeLabel: String
}

final class UploadLiveActivity {
  static let shared = UploadLiveActivity()

  /// Only uploads at least this big get a Live Activity.
  static let minBytes: Int64 = 15 * 1024 * 1024
  private static let maxConcurrent = 2

  private let lock = NSLock()
  private var lastPush: [String: (progress: Double, at: TimeInterval)] = [:]

  private static var compiledIn: Bool {
    (Bundle.main.object(forInfoDictionaryKey: "NSSupportsLiveActivities") as? Bool) == true
  }

  static var isAvailable: Bool {
    guard #available(iOS 16.1, *) else { return false }
    guard compiledIn else { return false }
    return ActivityAuthorizationInfo().areActivitiesEnabled
  }

  // MARK: - Labels (11 app languages; the widget only renders what we pass)

  private static let strings: [String: [String: String]] = [
    "pt": ["video": "Enviando vídeo", "photo": "Enviando foto", "audio": "Enviando áudio", "file": "Enviando arquivo", "done": "Enviado", "failed": "Falha no envio"],
    "pt-PT": ["video": "A enviar vídeo", "photo": "A enviar foto", "audio": "A enviar áudio", "file": "A enviar ficheiro", "done": "Enviado", "failed": "Falha no envio"],
    "en": ["video": "Sending video", "photo": "Sending photo", "audio": "Sending audio", "file": "Sending file", "done": "Sent", "failed": "Upload failed"],
    "es": ["video": "Enviando video", "photo": "Enviando foto", "audio": "Enviando audio", "file": "Enviando archivo", "done": "Enviado", "failed": "Error al enviar"],
    "fr": ["video": "Envoi de la vidéo", "photo": "Envoi de la photo", "audio": "Envoi de l’audio", "file": "Envoi du fichier", "done": "Envoyé", "failed": "Échec de l’envoi"],
    "de": ["video": "Video wird gesendet", "photo": "Foto wird gesendet", "audio": "Audio wird gesendet", "file": "Datei wird gesendet", "done": "Gesendet", "failed": "Senden fehlgeschlagen"],
    "it": ["video": "Invio del video", "photo": "Invio della foto", "audio": "Invio dell’audio", "file": "Invio del file", "done": "Inviato", "failed": "Invio non riuscito"],
    "hi": ["video": "वीडियो भेजा जा रहा है", "photo": "फ़ोटो भेजी जा रही है", "audio": "ऑडियो भेजा जा रहा है", "file": "फ़ाइल भेजी जा रही है", "done": "भेजा गया", "failed": "भेजना विफल रहा"],
    "ja": ["video": "動画を送信中", "photo": "写真を送信中", "audio": "音声を送信中", "file": "ファイルを送信中", "done": "送信済み", "failed": "送信に失敗しました"],
    "id": ["video": "Mengirim video", "photo": "Mengirim foto", "audio": "Mengirim audio", "file": "Mengirim file", "done": "Terkirim", "failed": "Gagal mengirim"],
    "ar": ["video": "جارٍ إرسال الفيديو", "photo": "جارٍ إرسال الصورة", "audio": "جارٍ إرسال الصوت", "file": "جارٍ إرسال الملف", "done": "تم الإرسال", "failed": "فشل الإرسال"],
  ]

  private static func table(_ lang: String?) -> [String: String] {
    var candidates: [String] = []
    if let l = lang, !l.isEmpty { candidates.append(l) }
    candidates.append(contentsOf: Locale.preferredLanguages)
    for raw in candidates {
      let l = raw.replacingOccurrences(of: "_", with: "-")
      let lower = l.lowercased()
      if lower.hasPrefix("pt-pt") { return strings["pt-PT"]! }
      let base = String(lower.split(separator: "-").first ?? "")
      if let t = strings[base] { return t }
    }
    return strings["en"]!
  }

  private static func kind(contentType: String, filename: String) -> String {
    let ct = contentType.lowercased()
    if ct.hasPrefix("video/") { return "video" }
    if ct.hasPrefix("image/") { return "photo" }
    if ct.hasPrefix("audio/") { return "audio" }
    let ext = (filename as NSString).pathExtension.lowercased()
    if ["mp4", "mov", "m4v", "webm"].contains(ext) { return "video" }
    if ["jpg", "jpeg", "png", "heic", "heif", "gif", "webp"].contains(ext) { return "photo" }
    if ["m4a", "mp3", "aac", "ogg", "opus", "wav"].contains(ext) { return "audio" }
    return "file"
  }

  private static func sizeLabel(_ bytes: Int64) -> String {
    let f = ByteCountFormatter()
    f.allowedUnits = [.useMB, .useGB]
    f.countStyle = .file
    return f.string(fromByteCount: bytes)
  }

  // MARK: - API (any thread)

  func start(id: String, contentType: String, filename: String, totalSize: Int64, progress: Double, lang: String?) {
    guard totalSize >= Self.minBytes else { return }
    guard #available(iOS 16.1, *), Self.isAvailable else { return }
    let k = Self.kind(contentType: contentType, filename: filename)
    let t = Self.table(lang)
    let attrs = ChatyyUploadAttributes(
      transferId: id,
      kind: k,
      title: t[k] ?? t["file"] ?? "Chatyy",
      doneLabel: t["done"] ?? "",
      failedLabel: t["failed"] ?? "",
      sizeLabel: Self.sizeLabel(totalSize)
    )
    let state = ChatyyUploadAttributes.ContentState(progress: max(0, min(1, progress)), status: "uploading")
    lock.lock(); lastPush[id] = (state.progress, Date().timeIntervalSince1970); lock.unlock()
    Task {
      let running = Activity<ChatyyUploadAttributes>.activities
      if running.contains(where: { $0.attributes.transferId == id }) { return }
      if running.filter({ $0.activityState == .active }).count >= Self.maxConcurrent { return }
      do {
        if #available(iOS 16.2, *) {
          _ = try Activity.request(attributes: attrs, content: ActivityContent(state: state, staleDate: nil), pushType: nil)
        } else {
          _ = try Activity.request(attributes: attrs, contentState: state, pushType: nil)
        }
      } catch {
        print("[UploadLiveActivity] request failed: \(error)")
      }
    }
  }

  /// After a (background) relaunch: re-attach to activities still on screen so
  /// progress updates resume for them.
  func adoptRunning() {
    guard #available(iOS 16.1, *), Self.compiledIn else { return }
    Task {
      let ids = Activity<ChatyyUploadAttributes>.activities
        .filter { $0.activityState == .active }
        .map { $0.attributes.transferId }
      self.seed(ids)
    }
  }

  private func seed(_ ids: [String]) {
    lock.lock()
    for id in ids where lastPush[id] == nil { lastPush[id] = (0, 0) }
    lock.unlock()
  }

  /// Throttled: pushes when progress moved ≥3 points or 2 s passed.
  func update(id: String, progress: Double) {
    guard #available(iOS 16.1, *), Self.compiledIn else { return }
    let now = Date().timeIntervalSince1970
    lock.lock()
    guard let last = lastPush[id] else { lock.unlock(); return } // never started for this id
    if progress - last.progress < 0.03 && now - last.at < 2.0 { lock.unlock(); return }
    lastPush[id] = (progress, now)
    lock.unlock()
    let state = ChatyyUploadAttributes.ContentState(progress: max(0, min(1, progress)), status: "uploading")
    Task {
      for a in Activity<ChatyyUploadAttributes>.activities where a.attributes.transferId == id {
        if #available(iOS 16.2, *) {
          await a.update(ActivityContent(state: state, staleDate: nil))
        } else {
          await a.update(using: state)
        }
      }
    }
  }

  /// Upload finished (any outcome). Also called after a background relaunch,
  /// so it looks the activity up by id instead of relying on memory.
  func finish(id: String, success: Bool, progress: Double) {
    guard #available(iOS 16.1, *), Self.compiledIn else { return }
    lock.lock(); lastPush.removeValue(forKey: id); lock.unlock()
    let state = ChatyyUploadAttributes.ContentState(
      progress: success ? 1.0 : max(0, min(1, progress)),
      status: success ? "done" : "failed"
    )
    let dismissAt = Date().addingTimeInterval(success ? 4 : 30)
    Task {
      for a in Activity<ChatyyUploadAttributes>.activities where a.attributes.transferId == id {
        if #available(iOS 16.2, *) {
          await a.end(ActivityContent(state: state, staleDate: nil), dismissalPolicy: .after(dismissAt))
        } else {
          await a.end(using: state, dismissalPolicy: .after(dismissAt))
        }
      }
    }
  }
}
