/**
 * Expo Config Plugin: Android AsyncStorage SQLite ceiling
 *
 * `@react-native-async-storage/async-storage` on Android reads
 * `AsyncStorage_db_size_in_MB` from the ROOT gradle.properties
 * (node_modules/@react-native-async-storage/async-storage/android/config.gradle
 * → getDatabaseSize()). When unset the SQLite DB is capped at 6 MB and every
 * setItem past that fails silently ("database or disk is full") — the chat
 * accelerator alone budgets 40 MB (services/smartChatCache.js) so the on-disk
 * cache was being truncated on heavy users.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so the
 * property MUST come from a config plugin. expo-build-properties 55.0.14 has
 * no `extraGradleProperties` option (only extraMavenRepos), hence this plugin.
 *
 * We do NOT enable `AsyncStorage_useNextStorage` (Room/KSP backend): it pulls
 * in a KSP + Room dependency chain and still goes through SQLite/CursorWindow,
 * so it buys nothing for the 2 MB-per-row limit (handled in JS by
 * services/mmkv.js) while adding build risk.
 *
 * Idempotent: re-running prebuild updates the value in place.
 * iOS is untouched (AsyncStorage on iOS is file-backed, no size cap).
 */
const { withGradleProperties } = require('expo/config-plugins');

const DEFAULT_DB_SIZE_MB = 64;

function withAsyncStorageSize(config, props = {}) {
  const sizeMB = Number.isFinite(Number(props.dbSizeMB)) && Number(props.dbSizeMB) > 0
    ? Math.floor(Number(props.dbSizeMB))
    : DEFAULT_DB_SIZE_MB;

  return withGradleProperties(config, (config) => {
    const items = config.modResults;
    const upsert = (key, value) => {
      const existing = items.find((it) => it.type === 'property' && it.key === key);
      if (existing) {
        existing.value = String(value);
      } else {
        items.push({
          type: 'comment',
          value: `${key}: set by plugins/withAsyncStorageSize.js (Android AsyncStorage SQLite ceiling)`,
        });
        items.push({ type: 'property', key, value: String(value) });
      }
    };
    upsert('AsyncStorage_db_size_in_MB', sizeMB);
    // Run AsyncStorage's SQLite work on its own executor instead of RN's
    // shared native-modules thread — a 1+ MB multiGet/multiSet no longer
    // stalls every other native module call during cold start.
    upsert('AsyncStorage_dedicatedExecutor', 'true');
    return config;
  });
}

module.exports = withAsyncStorageSize;
module.exports.DEFAULT_DB_SIZE_MB = DEFAULT_DB_SIZE_MB;
