/**
 * Expo config plugin — withMediapipeMlkitDedup
 * ============================================
 * Lets `MediaPipeTasksVision` (call-screen background blur, BackgroundProcessor.swift
 * via modules/expo-callkit/ios/ExpoCallKit.podspec) and `GoogleMLKit/FaceDetection`
 * (Status AR face filters, pulled by react-native-vision-camera-face-detector)
 * CO-EXIST in the same iOS binary. Both must keep working — this plugin removes the
 * `ld: NNN duplicate symbols` link failure WITHOUT dropping either pod.
 *
 * ── Root cause (verified) ─────────────────────────────────────────────────
 * MediaPipe's `MediaPipeTasksCommon` pod ships its compiled MediaPipe graph as a
 * STANDALONE static archive that the pod force-loads:
 *
 *     -force_load "$(PODS_ROOT)/MediaPipeTasksCommon/frameworks/graph_libraries/
 *                  libMediaPipeTasksCommon_device_graph.a"   (or _simulator_graph.a)
 *
 * That archive statically embeds its OWN copies of common third-party C++ objects —
 * glog (logging.o), protobuf (wire_format_lite.o), absl, etc. The SAME objects are
 * ALSO present in (a) the `MediaPipeTasksCommon.framework` binary and (b) React
 * Native's own `glog` pod / the protobuf that GoogleMLKit + Firebase drag in. When
 * MLKit / vision-camera-face-detector is also linked (it forces `use_frameworks!`
 * static linkage), the linker sees the force_loaded graph archive AND those other
 * copies and aborts:
 *
 *     ld: warning: ignoring duplicate libraries: '-force_load .../libMediaPipeTasksCommon_simulator_graph.a'
 *     ld: duplicate symbol 'google::base::Logger::~Logger()' in:
 *           libMediaPipeTasksCommon_simulator_graph.a(logging.o)
 *           libglog.a(logging.o)
 *     ld: duplicate symbol 'google::protobuf::internal::WireFormatLite::...' in:
 *           libMediaPipeTasksCommon_device_graph.a(wire_format_lite.o)
 *           MediaPipeTasksCommon.framework/MediaPipeTasksCommon(wire_format_lite.o)
 *
 * Sources confirming this exact RN/Expo collision and the underlying double-embed:
 *   - github.com/google-ai-edge/mediapipe/issues/6004  (Expo RN: glog dup symbol +
 *     "ignoring duplicate libraries -force_load .../_simulator_graph.a", crash in
 *     google::LogDestination::LogToSinks)
 *   - github.com/google-ai-edge/mediapipe/issues/5342  (MediaPipeTasksVision +
 *     GoogleMLKit/FaceDetection → duplicate symbol in libMediaPipeTasksCommon_
 *     device_graph.a vs MediaPipeTasksCommon.framework)
 *   - github.com/google-ai-edge/mediapipe/issues/4797 / #5051 / #5125 (same
 *     double-embed pattern vs OpenCV / TensorFlowLite)
 *
 * ── The fix ───────────────────────────────────────────────────────────────
 * Surgically delete the duplicated object files (glog + protobuf + absl logging /
 * wire-format objects) from MediaPipe's `*_graph.a` archives with `ar -d`, AFTER
 * `pod install` lays them down. Those exact symbols still resolve from exactly ONE
 * place (RN's glog pod + MediaPipeTasksCommon.framework's own copy + GoogleMLKit's
 * protobuf), so:
 *   - MediaPipeTasksVision stays fully linked (BackgroundProcessor blur works).
 *   - GoogleMLKit/FaceDetection stays fully linked (Status AR filters work).
 *   - Only the REDUNDANT copies inside the force_loaded graph archive are removed,
 *     leaving a single definition of each conflicting symbol → link succeeds.
 *
 * We strip a known, conservative allow-list of duplicate-prone object files (glog
 * logging/* and protobuf wire_format/common). MediaPipe's actual graph code (the
 * tasks/inference objects) is untouched, so the segmenter still runs.
 *
 * This runs as a Ruby `post_install` step injected into the Podfile (the file is
 * regenerated by `expo prebuild` in CI, so a raw edit would not survive — hence the
 * plugin). CocoaPods only allows ONE `post_install` hook, and the RN template
 * already emits one, so — exactly like plugins/withFixResourceSigning.js — we INJECT
 * our code inside that existing `post_install do |installer| ... react_native_post_install(...) ... end`
 * block rather than adding a second top-level hook (which CocoaPods rejects with
 * "Specifying multiple post_install hooks is unsupported").
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const HOOK_MARKER = '# --- withMediapipeMlkitDedup (merged) ---';

// Ruby injected into the existing post_install block. `installer` is in scope.
// We locate the MediaPipeTasksCommon graph_libraries dir under Pods/ and strip the
// duplicate-prone object files from each *_graph.a archive using `ar -d`.
const INJECT_BODY = `
    ${HOOK_MARKER}
    # Strip duplicate glog/protobuf object files that MediaPipe's force-loaded
    # *_graph.a archives statically re-embed, so they don't collide with RN's glog,
    # MediaPipeTasksCommon.framework, and GoogleMLKit's protobuf at link time.
    # Keeps BOTH MediaPipeTasksVision (call blur) and GoogleMLKit/FaceDetection
    # (Status AR) fully linked. See plugins/withMediapipeMlkitDedup.js for the why.
    begin
      pods_root = installer.sandbox.root.to_s
      graph_dir = File.join(pods_root, 'MediaPipeTasksCommon', 'frameworks', 'graph_libraries')
      # Object files known to be re-embedded by the graph archive AND present in
      # libglog.a / MediaPipeTasksCommon.framework / MLKit's protobuf. Removing the
      # redundant copies leaves exactly one definition each.
      dup_objects = %w[
        logging.o
        raw_logging.o
        vlog_is_on.o
        wire_format_lite.o
        common.o
      ]
      if Dir.exist?(graph_dir)
        Dir.glob(File.join(graph_dir, 'libMediaPipeTasksCommon_*_graph.a')).each do |archive|
          # List members actually present, then delete only the duplicate-prone ones.
          present = \`ar -t "#{archive}" 2>/dev/null\`.split("\\n").map(&:strip)
          to_delete = dup_objects.select { |o| present.include?(o) }
          unless to_delete.empty?
            system('ar', '-d', archive, *to_delete)
            Pod::UI.puts "[withMediapipeMlkitDedup] stripped #{to_delete.join(', ')} from #{File.basename(archive)}".green rescue nil
          end
        end
      else
        Pod::UI.puts "[withMediapipeMlkitDedup] MediaPipeTasksCommon graph_libraries not found at #{graph_dir} (skipping)".yellow rescue nil
      end
    rescue => e
      Pod::UI.warn "[withMediapipeMlkitDedup] dedup step failed: #{e.message}" rescue nil
    end
`;

module.exports = function withMediapipeMlkitDedup(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      if (!fs.existsSync(podfilePath)) return cfg;
      let contents = fs.readFileSync(podfilePath, 'utf8');
      if (contents.includes(HOOK_MARKER)) return cfg;

      // Inject right AFTER the `post_install do |installer|` opening line, INSIDE
      // the existing block. CocoaPods allows only ONE post_install hook, and the RN
      // template (plus withFixResourceSigning, which also injects at the top of the
      // block) already emits one. Anchoring on the OPENING line — not on
      // `react_native_post_install(` — is robust regardless of what other plugins
      // injected first (the previous regex required react_native_post_install to be
      // the first statement, which broke once withFixResourceSigning landed above it,
      // causing a SECOND hook to be appended → "multiple post_install hooks
      // unsupported"). Our begin/rescue body is valid anywhere in the block.
      const openRe = /(post_install do \|installer\|[^\n]*\n)/;
      if (openRe.test(contents)) {
        contents = contents.replace(openRe, `$1${INJECT_BODY}\n`);
      } else {
        // Fallback: no post_install present at all — safe to append our own.
        contents += `\npost_install do |installer|${INJECT_BODY}end\n`;
      }
      fs.writeFileSync(podfilePath, contents);
      return cfg;
    },
  ]);
};
