package expo.modules.nativetoolkit

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.net.Uri
import android.util.Log
import androidx.core.content.LocusIdCompat
import androidx.core.content.pm.ShortcutInfoCompat
import androidx.core.content.pm.ShortcutManagerCompat
import androidx.core.graphics.drawable.IconCompat
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import java.io.File
import java.net.URLEncoder
import java.security.MessageDigest

/**
 * [2026-10-08 android-otp-shortcuts] Launcher long-press shortcuts (Android).
 *
 * Static shortcuts (Nova conversa / Câmera / Escrever e-mail) live in
 * res/xml/chatyy_shortcuts.xml, generated by plugins/with-app-shortcuts.js.
 * This module only manages the DYNAMIC "recent conversations" set.
 *
 * Coexistence with modules/expo-callkit ChatMessagingStyleHandler:
 *   - Same id scheme ("chat_<conversationId>") and same deep link shape
 *     (onemundomail://chat-conversation?id=…&type=…), so a conversation that
 *     already has a notification shortcut is UPDATED in place (never
 *     duplicated) and both keep long-lived + LocusId + conversation category.
 *   - Avatar comes from the callkit on-disk cache (cacheDir/chat_avatars,
 *     md5(url).png) read-only — never downloads here; falls back to a
 *     letter avatar.
 *   - Stale ids that WE pushed earlier are removed from the dynamic set with
 *     removeDynamicShortcuts (long-lived → they stay cached, so a live
 *     MessagingStyle notification referencing them keeps working).
 */
class ExpoAppShortcutsModule : Module() {

  companion object {
    private const val TAG = "ExpoAppShortcuts"
    private const val PREFS = "chatyy_app_shortcuts"
    private const val KEY_IDS = "dynamic_ids"
    private const val SCHEME = "onemundomail"
    private const val AVATAR_HOST = "https://chatyy.com.br"
    private const val MAX_RECENTS = 4
    // [2026-10-09 notif-native] Sharing Shortcuts — must match the
    // <share-target> category written by plugins/with-app-shortcuts.js.
    private const val SHARE_CATEGORY_SUFFIX = ".category.SHARE_TARGET"
    private const val CONVERSATION_CATEGORY = "android.shortcut.conversation"
    private const val SHARE_TARGET_TTL_MS = 10L * 60 * 1000
    @Volatile private var pendingShareShortcut: String? = null
    @Volatile private var pendingShareAt: Long = 0L
    private const val ICON_PX = 192
    private val PALETTE = intArrayOf(
      0xFF2563EB.toInt(), 0xFF10B981.toInt(), 0xFFF59E0B.toInt(), 0xFFEF4444.toInt(),
      0xFF8B5CF6.toInt(), 0xFF0EA5E9.toInt(), 0xFFEC4899.toInt(), 0xFF14B8A6.toInt(),
    )
  }

  private val ctx: Context? get() = appContext.reactContext?.applicationContext

  override fun definition() = ModuleDefinition {
    Name("ExpoAppShortcuts")
    Events("onShortcut")

    // items: [{ id, name, type: 'direct'|'group', email?, avatarUrl?, acct? }]
    // Returns the number of shortcuts actually published.
    AsyncFunction("setRecentConversations") { items: List<Map<String, Any?>> ->
      var published = 0
      val c = ctx
      if (c != null) {
        try {
          published = publishRecents(c, items)
        } catch (t: Throwable) {
          Log.w(TAG, "setRecentConversations failed: ${t.message}")
        }
      }
      published
    }

    Function("clear") {
      val c = ctx
      if (c != null) {
        try {
          removeOurs(c, emptySet())
        } catch (t: Throwable) {
          Log.w(TAG, "clear failed: ${t.message}")
        }
      }
    }

    // iOS parity (cold-launch shortcut URL). Android shortcuts are plain
    // ACTION_VIEW deep links handled by Linking/expo-router → always null.
    Function("getPendingShortcut") { null as String? }

    // [2026-10-09 notif-native] Direct Share: the system share sheet row of
    // recent chats delivers ACTION_SEND with EXTRA_SHORTCUT_ID = "chat_<id>".
    // Warm start → OnNewIntent; cold start → the activity's launch intent.
    OnNewIntent { intent -> captureShareShortcut(intent) }

    // Returns { conversationId } once (≤ 10 min old), else null.
    Function("consumeShareTarget") {
      try { appContext.currentActivity?.intent?.let { captureShareShortcut(it) } } catch (_: Throwable) {}
      val id = pendingShareShortcut
      val fresh = id != null && System.currentTimeMillis() - pendingShareAt < SHARE_TARGET_TTL_MS
      pendingShareShortcut = null
      try { appContext.currentActivity?.intent?.removeExtra(ShortcutManagerCompat.EXTRA_SHORTCUT_ID) } catch (_: Throwable) {}
      if (fresh && id != null && id.startsWith("chat_") && id.length > 5) {
        mapOf("conversationId" to id.removePrefix("chat_"))
      } else null
    }

    // Ranking signal for the share sheet / launcher (call on send).
    Function("reportConversationUsed") { conversationId: String ->
      val c = ctx
      if (c != null && conversationId.isNotBlank()) {
        try { ShortcutManagerCompat.reportShortcutUsed(c, "chat_" + conversationId.trim()) } catch (_: Throwable) {}
      }
    }
  }

  private fun captureShareShortcut(intent: Intent) {
    val action = intent.action ?: return
    if (action != Intent.ACTION_SEND && action != Intent.ACTION_SEND_MULTIPLE) return
    val sid = try { intent.getStringExtra(ShortcutManagerCompat.EXTRA_SHORTCUT_ID) } catch (_: Throwable) { null }
    if (!sid.isNullOrBlank()) {
      pendingShareShortcut = sid
      pendingShareAt = System.currentTimeMillis()
    }
  }

  private fun publishRecents(c: Context, items: List<Map<String, Any?>>): Int {
    if (ShortcutManagerCompat.isRateLimitingActive(c)) {
      Log.w(TAG, "rate limited — skipping")
      return 0
    }
    val maxAllowed = ShortcutManagerCompat.getMaxShortcutCountPerActivity(c)
    val limit = minOf(MAX_RECENTS, if (maxAllowed > 0) maxAllowed else MAX_RECENTS)
    val keep = LinkedHashSet<String>()
    var rank = 0
    for (item in items) {
      if (keep.size >= limit) break
      val convId = (item["id"] ?: "").toString().trim()
      if (convId.isEmpty()) continue
      val name = (item["name"] ?: "").toString().trim().ifEmpty { "Chatyy" }
      val isGroup = (item["type"] ?: "").toString() == "group"
      val email = (item["email"] ?: "").toString().trim()
      val acct = (item["acct"] ?: "").toString().trim()
      val avatarUrl = (item["avatarUrl"] ?: "").toString().trim()
      val id = "chat_$convId"
      var ok = false
      try {
        val uri = conversationUri(convId, isGroup, name, email, acct)
        val intent = Intent(Intent.ACTION_VIEW, uri).setPackage(c.packageName)
        // Callkit caches direct-chat avatars under its canonical get_avatar URL
        // (no cache-buster params) — try that key too for direct chats.
        val canonical = if (!isGroup && email.contains('@'))
          "$AVATAR_HOST/api/email.php?action=get_avatar&email=" + URLEncoder.encode(email, "UTF-8") else ""
        val bmp = cachedAvatar(c, avatarUrl) ?: cachedAvatar(c, canonical) ?: letterAvatar(name, convId)
        val info = ShortcutInfoCompat.Builder(c, id)
          .setShortLabel(name.take(25))
          .setLongLabel(name.take(60))
          .setLongLived(true)
          .setIntent(intent)
          .setLocusId(LocusIdCompat(id))
          .setCategories(setOf(CONVERSATION_CATEGORY, c.packageName + SHARE_CATEGORY_SUFFIX))
          .setRank(rank)
          .setIcon(IconCompat.createWithBitmap(bmp))
          .build()
        ShortcutManagerCompat.pushDynamicShortcut(c, info)
        ok = true
      } catch (t: Throwable) {
        Log.w(TAG, "push $id failed: ${t.message}")
      }
      if (ok) {
        keep.add(id)
        rank++
      }
    }
    removeOurs(c, keep)
    try {
      c.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit().putStringSet(KEY_IDS, HashSet(keep)).apply()
    } catch (_: Throwable) {
    }
    return keep.size
  }

  /** Removes dynamic shortcuts we published previously that are not in [keep]. */
  private fun removeOurs(c: Context, keep: Set<String>) {
    val prefs = c.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
    val prev = prefs.getStringSet(KEY_IDS, emptySet()) ?: emptySet()
    val stale = prev.filter { it !in keep }
    if (stale.isNotEmpty()) {
      try {
        ShortcutManagerCompat.removeDynamicShortcuts(c, stale)
      } catch (t: Throwable) {
        Log.w(TAG, "removeDynamicShortcuts failed: ${t.message}")
      }
    }
    if (keep.isEmpty()) {
      try {
        prefs.edit().remove(KEY_IDS).apply()
      } catch (_: Throwable) {
      }
    }
  }

  private fun conversationUri(convId: String, isGroup: Boolean, name: String, email: String, acct: String): Uri {
    val b = Uri.Builder().scheme(SCHEME).authority("chat-conversation")
      .appendQueryParameter("id", convId)
      .appendQueryParameter("type", if (isGroup) "group" else "direct")
    if (name.isNotEmpty()) b.appendQueryParameter("name", name)
    if (email.isNotEmpty()) b.appendQueryParameter("email", email)
    if (acct.isNotEmpty()) b.appendQueryParameter("acct", acct)
    b.appendQueryParameter("src", "shortcut")
    return b.build()
  }

  /** Read-only lookup in the expo-callkit avatar cache (cacheDir/chat_avatars/md5(absUrl).png). */
  private fun cachedAvatar(c: Context, url: String): Bitmap? {
    if (url.isEmpty()) return null
    val abs = when {
      url.startsWith("https://") -> url
      url.startsWith("/") -> AVATAR_HOST + url
      else -> return null
    }
    var bmp: Bitmap? = null
    try {
      val f = File(File(c.cacheDir, "chat_avatars"), md5(abs) + ".png")
      if (f.exists()) bmp = BitmapFactory.decodeFile(f.absolutePath)
    } catch (_: Throwable) {
      bmp = null
    }
    return bmp
  }

  private fun letterAvatar(name: String, seed: String): Bitmap {
    val out = Bitmap.createBitmap(ICON_PX, ICON_PX, Bitmap.Config.ARGB_8888)
    val canvas = Canvas(out)
    val bg = Paint(Paint.ANTI_ALIAS_FLAG)
    bg.color = PALETTE[Math.floorMod(seed.hashCode(), PALETTE.size)]
    canvas.drawCircle(ICON_PX / 2f, ICON_PX / 2f, ICON_PX / 2f, bg)
    val letter = name.trim().firstOrNull { it.isLetterOrDigit() }?.uppercaseChar()?.toString() ?: "C"
    val tp = Paint(Paint.ANTI_ALIAS_FLAG)
    tp.color = Color.WHITE
    tp.textSize = ICON_PX * 0.46f
    tp.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
    tp.textAlign = Paint.Align.CENTER
    val y = ICON_PX / 2f - (tp.descent() + tp.ascent()) / 2f
    canvas.drawText(letter, ICON_PX / 2f, y, tp)
    return out
  }

  private fun md5(s: String): String {
    val d = MessageDigest.getInstance("MD5").digest(s.toByteArray(Charsets.UTF_8))
    val sb = StringBuilder()
    for (b in d) sb.append(String.format("%02x", b))
    return sb.toString()
  }
}
