// CallLiveActivity.swift — [2026-10-07 ios-native] Live Activity / Dynamic
// Island for an ongoing 1:1 call ("Em ligação com Fulano · 03:12").
//
// App-side half. The UI lives in the ChatyyCallActivity WidgetKit extension
// generated by plugins/with-live-activity.js. Gated OFF by default:
//   • the extension + `NSSupportsLiveActivities` only exist when the build ran
//     with CHATYY_LIVE_ACTIVITY=1 (needs the com.onemundo.mail.CallActivity
//     provisioning profile — scripts/asc-create-liveactivity-profile.js);
//   • every entry point below checks that Info.plist key + the user's Live
//     Activities permission first, so on today's binaries this is a no-op.
//
// The elapsed time is rendered by `Text(timerInterval:)` in the widget, so we
// only push a state at connect and at end — no per-second updates, no push
// tokens, no background work.
//
// KEEP IN SYNC: `ChatyyCallAttributes` must match the copy embedded in
// plugins/with-live-activity.js field-for-field.

import Foundation
import ActivityKit

@available(iOS 16.1, *)
struct ChatyyCallAttributes: ActivityAttributes {
    public struct ContentState: Codable, Hashable {
        /// "active" | "ended"
        var status: String
        /// When the call connected — drives the self-updating timer.
        var connectedAt: Date
        var isVideo: Bool
    }
    var peerName: String
    var callId: String
}

final class CallLiveActivity {
    static let shared = CallLiveActivity()
    private var endObserver: NSObjectProtocol?

    private init() {
        // Every native hangup / remote-end / disconnect path posts this
        // (CallViewController.callEndedNotification).
        endObserver = NotificationCenter.default.addObserver(
            forName: Notification.Name("ExpoCallKitNativeCallEnded"),
            object: nil,
            queue: .main
        ) { note in
            CallLiveActivity.shared.callEnded(callId: note.userInfo?["callId"] as? String)
        }
    }

    /// Live Activities compiled in (plugin ON) and allowed by the user.
    static var isAvailable: Bool {
        guard #available(iOS 16.1, *) else { return false }
        guard (Bundle.main.object(forInfoDictionaryKey: "NSSupportsLiveActivities") as? Bool) == true else {
            return false
        }
        return ActivityAuthorizationInfo().areActivitiesEnabled
    }

    /// Call flipped to connected. Idempotent per callId; ends any stale
    /// activity from a previous call first.
    func callConnected(callId: String, peerName: String, isVideo: Bool, connectedAt: Date) {
        guard #available(iOS 16.1, *), Self.isAvailable else { return }
        let name = peerName.trimmingCharacters(in: .whitespacesAndNewlines)
        let attrs = ChatyyCallAttributes(peerName: name.isEmpty ? "Chatyy" : name, callId: callId)
        let state = ChatyyCallAttributes.ContentState(status: "active", connectedAt: connectedAt, isVideo: isVideo)
        Task {
            var alreadyRunning = false
            for activity in Activity<ChatyyCallAttributes>.activities {
                if activity.attributes.callId == callId {
                    alreadyRunning = true
                } else {
                    await Self.end(activity, finalState: nil)
                }
            }
            if alreadyRunning { return }
            do {
                if #available(iOS 16.2, *) {
                    _ = try Activity.request(
                        attributes: attrs,
                        content: ActivityContent(state: state, staleDate: nil),
                        pushType: nil
                    )
                } else {
                    _ = try Activity.request(attributes: attrs, contentState: state, pushType: nil)
                }
                print("[CallLiveActivity] started callId=\(callId)")
            } catch {
                print("[CallLiveActivity] request failed: \(error)")
            }
        }
    }

    /// Call ended / torn down. Ends that call's activity (or every Chatyy call
    /// activity when callId is nil) immediately.
    func callEnded(callId: String? = nil) {
        guard #available(iOS 16.1, *) else { return }
        // No isAvailable gate here: if the user revoked the permission mid-
        // call, a running activity must still be ended.
        guard (Bundle.main.object(forInfoDictionaryKey: "NSSupportsLiveActivities") as? Bool) == true else { return }
        Task {
            for activity in Activity<ChatyyCallAttributes>.activities {
                if let callId = callId, !callId.isEmpty, activity.attributes.callId != callId { continue }
                var finalState: ChatyyCallAttributes.ContentState
                if #available(iOS 16.2, *) {
                    finalState = activity.content.state
                } else {
                    finalState = activity.contentState
                }
                finalState.status = "ended"
                await Self.end(activity, finalState: finalState)
            }
        }
    }

    @available(iOS 16.1, *)
    private static func end(_ activity: Activity<ChatyyCallAttributes>,
                            finalState: ChatyyCallAttributes.ContentState?) async {
        if #available(iOS 16.2, *) {
            let content = finalState.map { ActivityContent(state: $0, staleDate: nil) }
            await activity.end(content, dismissalPolicy: .immediate)
        } else {
            await activity.end(using: finalState, dismissalPolicy: .immediate)
        }
    }
}
