import { NativeModule, requireNativeModule, EventEmitter } from 'expo-modules-core';

interface ExpoCallKitEvents {
  onCallAnswered: { callId: string };
  onCallEnded: { callId: string };
  onVoipTokenReceived: { token: string };
  onIncomingCall: { callId: string; callerName: string; hasVideo: boolean };
  // [bug 2026-05-15 #9] Fired when CXProvider:didActivate runs, i.e. CallKit
  // now owns the AVAudioSession. /call uses this on the CallKit accept path
  // to gate Room.connect — otherwise LiveKit's audio session setup races
  // CallKit's and we end up with competing setCategory paths.
  onCallKitAudioActivated: Record<string, never>;
  onCallKitAudioDeactivated: Record<string, never>;
  // [#992 Stage 1 Android + Stage 2 iOS] Native LiveKit Room events. Shape is
  // a union of the two platforms — some fields are platform-specific. JS
  // listeners should treat all fields as optional and branch as needed.
  onLkConnected: { callId?: string; snapshot?: Record<string, any>; roomName?: string; localIdentity?: string };
  onLkParticipantConnected: { callId?: string; identity: string; sid?: string; name?: string };
  onLkParticipantDisconnected: { callId?: string; identity: string };
  onLkTrackSubscribed: { callId?: string; identity?: string; participantIdentity?: string; kind: string; sid?: string; trackSid?: string };
  onLkTrackUnsubscribed: { callId?: string; identity?: string; participantIdentity?: string; kind: string; trackSid?: string };
  onLkConnectionQuality: { callId?: string; identity?: string; participantIdentity?: string; quality: string };
  onLkDisconnected: { callId?: string; reason: string };
  onLkDataReceived: { callId?: string; identity?: string; data: string };
  onLkError: { callId?: string; message: string };
  // __chatyy_native_call_sync 2026-05-19 — native call-state mirrors so JS
  // analytics, recording banner, OngoingCallBar, and any hybrid /call overlay
  // share state with the native Compose UI (Android) / SwiftUI CallView (iOS).
  // Native UI is the single source of truth; these events propagate to JS.
  onLkLocalAudioChanged: { enabled: boolean };
  onLkLocalVideoChanged: { enabled: boolean };
  onLkSpeakerChanged: { enabled: boolean };
  onLkCameraFlipped: { front: boolean };
  onAudioRouteChanged: { route: 'speaker' | 'earpiece' | 'bluetooth' | 'headset' };
  onCallHoldChanged: { held: boolean };
  onPipChanged: { inPip: boolean };
  /** [share outbox feedback, 2026-05-19] Fired when the native iOS
   *  ShareExtension finishes a share session. JS reads entries via
   *  getShareOutbox() and refreshes the chat list for each affected
   *  conversation, then calls clearShareOutbox() to drain. */
  onShareDidSend: {
    entries: Array<{ msg_id: string; conv_id: string; sent_at: number; type: string }>;
    count: number;
  };
}

export interface ShareOutboxEntry {
  /** Client-side UUID generated by the ShareExtension; not the server msg_id
   *  (which the extension doesn't always parse out of the upload response).
   *  Used for client-side dedup so we don't double-refresh the same send. */
  msg_id: string;
  /** Server conversation id (numeric string). The chat list / open
   *  conversation matching this id should be refreshed. */
  conv_id: string;
  /** Unix epoch seconds the share extension completed the send. */
  sent_at: number;
  /** "text" | "image" | "video" | "url" | "file" — mirrors PayloadKind on
   *  the Swift side. Useful for the JS layer to decide which cache to bump. */
  type: string;
}

declare class ExpoCallKitModuleType extends NativeModule<ExpoCallKitEvents> {
  setup(): Promise<void>;
  displayIncomingCall(callId: string, callerName: string, hasVideo: boolean): Promise<void>;
  endCall(callId: string): void;
  registerVoipPush(): void;
  getVoipToken(): string | null;
  getDiagnostics(): Record<string, any>;
  consumePendingEvents(): Array<Record<string, any>>;
  consumePendingCall(): { callId: string; callerName: string; hasVideo: boolean } | null;
  // [#992 Stage 1+2] Native LiveKit Room control. Positional args; both
  // platforms accept this shape (Android Kotlin via @AsyncFunction direct
  // positional; iOS Swift adapts internally).
  persistAuthForNativeCall(token: string, baseUrl: string): Promise<void>;
  persistPendingLkToken(roomName: string, token: string, url: string): Promise<void>;
  isNativeRoomConnected(): boolean;
  adoptNativeRoom(callId: string): Promise<Record<string, any> | null>;
  lkConnect(url: string, token: string, callId: string, hasVideo: boolean): Promise<void>;
  lkDisconnect(): Promise<void>;
  lkSetMicEnabled(enabled: boolean): Promise<void>;
  lkSetCameraEnabled(enabled: boolean): Promise<void>;
  // [host-mute, 2026-05-17] Host-issued mute of a remote participant. See
  // `ExpoCallKitModule.muteParticipant` on both platforms — the actual HTTP
  // path lives in services/api.js#chatCallMuteParticipant; this native shim
  // is a forward-compat hook for when NativeCallRoom v2 owns the LK Room.
  muteParticipant(roomName: string, identity: string): Promise<boolean>;
  // [#992 Stage 3] Launches the full-native call screen (CallActivity on
  // Android, CallViewController hosting SwiftUI CallView on iOS). Replaces
  // the RN /call.js screen for outgoing/incoming calls.
  openNativeCall(
    callId: string,
    callerName: string,
    callerEmail: string,
    hasVideo: boolean,
    lkUrl: string | null,
    lkToken: string | null
  ): Promise<void>;
  // [Stage #996] Native outgoing-call entry point. On iOS submits a
  // CXStartCallAction (so CallKit tracks the call in Recents / lock screen)
  // and then presents CallViewController; on Android starts CallActivity
  // with EXTRA_IS_OUTGOING=true so it fires call_invite + plays ringback.
  // The single-object signature is what JS callers prefer (vs. the long
  // positional list of openNativeCall) — Expo Modules adapts maps to the
  // platform native dictionary/Map shape automatically.
  startOutgoingCall(params: {
    callee_email: string;
    callee_name?: string;
    /** [#1176 polish, 2026-05-18] HTTPS URL of the callee's avatar
     *  (typically the backend get_avatar?email=... endpoint). Passed in so
     *  the native call screen can render the real photo while LiveKit Room
     *  is still connecting — instead of just the initial letter. */
    callee_avatar?: string;
    caller_name?: string;
    is_video: boolean;
    room_name?: string;
    conversation_id?: string;
    call_id?: string;
    lk_url?: string;
    lk_token?: string;
  }): Promise<boolean>;
  // [2026-05-16] Group-call scaffold (Android). Launches GroupCallActivity
  // with an N×N grid of tiles, one per remote participant. Participants are
  // serialized as JSON so the native side can pre-seed placeholder tiles
  // before LiveKit's ParticipantConnected events fire. iOS counterpart will
  // mirror this signature once SwiftUI GroupCallView lands.
  openGroupCall(
    roomName: string,
    lkUrl: string,
    lkToken: string,
    participantsJson: string,
    hasVideo: boolean
  ): Promise<void>;

  // [2026-05-17 RNNoise] Per-user ML noise suppression toggle. Default ON.
  // Returns the current state from native SharedPreferences (Android) /
  // App Group UserDefaults (iOS). Setting the value applies immediately to
  // any active Room.
  setNoiseSuppression(enabled: boolean): boolean;
  getNoiseSuppression(): boolean;
  isNoiseSuppressionAvailable(): boolean;

  // [#1205 live muting fix, 2026-05-19] Reset audio session before live
  // broadcast getUserMedia. Wipes a leaked MODE_IN_COMMUNICATION (Android)
  // or `.voiceChat` AVAudioSession (iOS) that a prior call left behind —
  // those modes route the mic through voice-call AEC which over-suppresses
  // the one-way send pattern a live broadcast uses, manifesting as the
  // host's audio progressively going silent within ~5s of going live.
  prepareAudioForLive(): boolean;

  // [2026-05-17 Background blur / virtual background] Per-user background
  // effect. `mode` is one of: 'off', 'blur_low', 'blur_medium', 'blur_high',
  // 'image'. `imageAsset` is required when mode === 'image' (one of the
  // built-in wallpapers from getBackgroundWallpapers()).
  setBackgroundMode(mode: string, imageAsset?: string | null): boolean;
  getBackgroundMode(): { mode: string; imageAsset: string };
  isBackgroundProcessorAvailable(): boolean;
  getBackgroundWallpapers(): string[];

  // [2026-05-17 screen share] Native screen-share entry. On iOS this pops the
  // ReplayKit broadcast picker; on Android the MediaProjection consent dialog.
  // `audioShare` only respected on iOS today — Android system-audio capture
  // requires AudioPlaybackCaptureConfiguration which is pending. Returns true
  // when the system dialog was displayed; the actual broadcast lifecycle is
  // observed via the existing onBroadcastStarted / onBroadcastStopped events
  // on modules/expo-screen-share.
  startScreenshare(audioShare: boolean): Promise<boolean>;
  stopScreenshare(): Promise<boolean>;

  // [P0 2026-05-18 #1132] Eagerly open the native CallSignalWs so it can
  // receive inbound `call_invite` frames and ring CallKit (iOS) /
  // CallRingingService (Android) even if the JS WS path is broken/paused.
  // Idempotent.
  warmCallSignalWs(): void;

  /** [share outbox feedback, 2026-05-19] Drain the App Group share_outbox
   *  queue written by the native iOS ShareExtension. iOS-only; returns an
   *  empty array on Android / when the module isn't available. */
  getShareOutbox?(): ShareOutboxEntry[];
  /** [share outbox feedback, 2026-05-19] Clear the App Group share_outbox
   *  queue after JS has processed the entries. iOS-only no-op elsewhere. */
  clearShareOutbox?(): void;
}

export interface OpenNativeCallParams {
  callId: string;
  callerName: string;
  callerEmail: string;
  hasVideo: boolean;
  lkUrl?: string;
  lkToken?: string;
}

/** Group-call invitee. `email` is the LiveKit participant identity (stable
 *  across reconnects); `name` is the display label rendered on the tile;
 *  `avatarUrl` is reserved for the avatar fallback (not yet wired in the
 *  Android scaffold — it renders the first letter of `name` for now). */
export interface GroupCallParticipant {
  email: string;
  name: string;
  avatarUrl?: string;
}

export interface OpenGroupCallParams {
  roomName: string;
  lkUrl: string;
  lkToken: string;
  participants: GroupCallParticipant[];
  hasVideo: boolean;
}

let mod: ExpoCallKitModuleType | null = null;
let emitter: EventEmitter | null = null;

function getModule(): ExpoCallKitModuleType | null {
  if (mod) return mod;
  try {
    mod = requireNativeModule<ExpoCallKitModuleType>('ExpoCallKit');
    return mod;
  } catch {
    return null;
  }
}

function getEmitter(): EventEmitter | null {
  if (emitter) return emitter;
  const m = getModule();
  if (!m) return null;
  try {
    emitter = new EventEmitter(m);
    return emitter;
  } catch {
    return null;
  }
}

export async function setup(): Promise<boolean> {
  const m = getModule();
  if (!m) return false;
  try {
    await m.setup();
    return true;
  } catch (e) {
    console.warn('[ExpoCallKit] setup error:', e);
    return false;
  }
}

export async function displayIncomingCall(callId: string, callerName: string, hasVideo: boolean): Promise<boolean> {
  const m = getModule();
  if (!m) return false;
  try {
    await m.displayIncomingCall(callId, callerName, hasVideo);
    return true;
  } catch (e) {
    console.warn('[ExpoCallKit] displayIncomingCall error:', e);
    return false;
  }
}

export function endCall(callId: string): void {
  const m = getModule();
  if (!m) return;
  try {
    m.endCall(callId);
  } catch {}
}

export function registerVoipPush(): void {
  const m = getModule();
  if (!m) return;
  try {
    m.registerVoipPush();
  } catch {}
}

export function onCallAnswered(cb: (data: { callId: string }) => void): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onCallAnswered', cb);
  return () => sub.remove();
}

export function onCallEnded(cb: (data: { callId: string }) => void): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onCallEnded', cb);
  return () => sub.remove();
}

export function onVoipTokenReceived(cb: (data: { token: string }) => void): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onVoipTokenReceived', cb);
  return () => sub.remove();
}

export function onIncomingCall(cb: (data: { callId: string; callerName: string; hasVideo: boolean }) => void): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onIncomingCall', cb);
  return () => sub.remove();
}

export function onCallKitAudioActivated(cb: () => void): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onCallKitAudioActivated', cb);
  return () => sub.remove();
}

export function onCallKitAudioDeactivated(cb: () => void): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onCallKitAudioDeactivated', cb);
  return () => sub.remove();
}

/**
 * [Bridge #2/#3 2026-05-19] Subscribe to native PiP enter/exit on the call
 * surface. Fires whenever CallActivity / CallViewController toggles PiP.
 * Returns an unsubscribe function; safe to call before the native module
 * is loaded (returns a no-op unsubscribe).
 */
export function onPipChanged(cb: (data: { inPip: boolean }) => void): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onPipChanged', cb);
  return () => sub.remove();
}

export function getVoipToken(): string | null {
  const m = getModule();
  if (!m) return null;
  try {
    return m.getVoipToken();
  } catch {
    return null;
  }
}

export function getDiagnostics(): Record<string, any> | null {
  const m = getModule();
  if (!m) return null;
  try {
    return m.getDiagnostics();
  } catch {
    return null;
  }
}

export function consumePendingEvents(): Array<Record<string, any>> {
  const m = getModule();
  if (!m) return [];
  try {
    return m.consumePendingEvents() || [];
  } catch {
    return [];
  }
}

export function consumePendingCall(): { callId: string; callerName: string; hasVideo: boolean } | null {
  const m = getModule();
  if (!m) return null;
  try {
    return m.consumePendingCall() || null;
  } catch {
    return null;
  }
}

// ─── Native LiveKit Room (Stage 1+2 #992 #993) ───────────────────────────────
// Bridges the JS /call screen to the native-owned Room. Eliminates the
// 4-8s cold-start audio gap on Android. iOS Stage 2 lands the equivalent.

/** Stash auth token + API base URL into native SharedPreferences (Android)
 *  / App Group UserDefaults (iOS). Call from services/api.js setAuthTokenDirect
 *  so cold-start accept paths can fetch LK tokens without JS. */
export async function persistAuthForNativeCall(token: string, baseUrl: string): Promise<void> {
  const m = getModule();
  if (!m) return;
  try {
    await m.persistAuthForNativeCall(token, baseUrl);
  } catch (e) {
    console.warn('[ExpoCallKit] persistAuthForNativeCall error:', e);
  }
}

export async function persistPendingLkToken(roomName: string, token: string, url: string): Promise<void> {
  const m = getModule();
  if (!m) return;
  try {
    await m.persistPendingLkToken(roomName, token, url);
  } catch (e) {
    console.warn('[ExpoCallKit] persistPendingLkToken error:', e);
  }
}

export function isNativeRoomConnected(): boolean {
  const m = getModule();
  if (!m) return false;
  try { return !!m.isNativeRoomConnected(); } catch { return false; }
}

export async function adoptNativeRoom(callId: string): Promise<Record<string, any> | null> {
  const m = getModule();
  if (!m) return null;
  try {
    return (await m.adoptNativeRoom(callId)) ?? null;
  } catch {
    return null;
  }
}

export async function lkConnect(url: string, token: string, callId: string, hasVideo: boolean): Promise<void> {
  const m = getModule();
  if (!m) throw new Error('Native CallKit module unavailable');
  await m.lkConnect(url, token, callId, hasVideo);
}

export async function lkDisconnect(): Promise<void> {
  const m = getModule();
  if (!m) return;
  try { await m.lkDisconnect(); } catch {}
}

export async function lkSetMicEnabled(enabled: boolean): Promise<void> {
  const m = getModule();
  if (!m) return;
  try { await m.lkSetMicEnabled(enabled); } catch {}
}

export async function lkSetCameraEnabled(enabled: boolean): Promise<void> {
  const m = getModule();
  if (!m) return;
  try { await m.lkSetCameraEnabled(enabled); } catch {}
}

/** Host-issued mute of a remote participant. The native module is a thin
 *  shim today (the actual mute travels HTTP → WS → target client because
 *  NativeCallRoom is a stub on both platforms). Always returns true so
 *  callers don't branch on the no-op case; the HTTP layer surfaces the real
 *  outcome via `chatCallMuteParticipant`. */
export async function muteParticipant(roomName: string, identity: string): Promise<boolean> {
  const m = getModule();
  if (!m) return false;
  try {
    return !!(await m.muteParticipant(roomName, identity));
  } catch {
    return false;
  }
}

/** Launches the full-native call screen. Replaces the RN /call.js screen for
 *  outgoing/incoming calls (CallActivity on Android, CallViewController +
 *  SwiftUI CallView on iOS). lkUrl/lkToken are optional — pass them when the
 *  caller already has a LiveKit room minted, otherwise the native side
 *  fetches via the auth persisted by persistAuthForNativeCall. */
export async function openNativeCall(params: OpenNativeCallParams): Promise<void> {
  const m = getModule();
  if (!m) throw new Error('Native CallKit module unavailable');
  await m.openNativeCall(
    params.callId,
    params.callerName,
    params.callerEmail,
    params.hasVideo,
    params.lkUrl ?? null,
    params.lkToken ?? null
  );
}

export interface StartOutgoingCallParams {
  /** Email of the person being called. Always required — used as the
   *  CXHandle on iOS and as the chat target on the WS layer. */
  calleeEmail: string;
  /** Display name shown on the native call screen while ringing. Defaults
   *  to the email when omitted. */
  calleeName?: string;
  /** [#1176 polish, 2026-05-18] Avatar URL shown on the native call screen
   *  while the LiveKit room is still negotiating. Without this the screen
   *  falls back to the initial letter. Typically populated via
   *  `api.getAvatarUrlForEmail(calleeEmail)` from the JS caller. */
  calleeAvatar?: string;
  /** Display name of the local user. Forwarded into call_invite so the
   *  callee's incoming-call UI can show "Maria está chamando…". */
  callerName?: string;
  /** True for video calls, false for audio-only. Drives the CXCallUpdate
   *  hasVideo flag on iOS and the LiveKit setCamera path on Android. */
  isVideo: boolean;
  /** LiveKit room name. Defaults to callId when omitted. Stick with callId
   *  unless you need a stable room across devices (e.g., bridging an
   *  existing meeting). */
  roomName?: string;
  /** Chat conversation row id. Used as the second key (alongside callId)
   *  when firing call_invite / call_end via CallSignalWs. Empty string is
   *  valid for dialer-style flows. */
  conversationId?: string;
  /** Server-side call id. Lets the JS layer pin a known value so the
   *  WS call_invite payload sent by the native side matches what the JS
   *  side reports to /api/call_notify. */
  callId?: string;
  /** LiveKit websocket URL — when JS already minted a token via
   *  chat_livekit_token, forward it here so the native side can connect
   *  the Room without an extra HTTP round trip. */
  lkUrl?: string;
  /** LiveKit access token (publisher grant). Pair with `lkUrl`. */
  lkToken?: string;
}

/** Stage #996 — kick off an outgoing call through the native CallKit /
 *  CallActivity flow. On iOS this submits a CXStartCallAction so the system
 *  tracks the call (Recents, lock-screen UI, audio session ownership) and
 *  presents CallViewController; on Android it starts CallActivity with the
 *  outgoing flag so it fires call_invite + plays the standard ringback
 *  tone. Returns true once the transaction was queued; the call lifecycle
 *  continues via the onCallAnswered / onCallEnded events.
 *
 *  Throws on iOS if no CXCallController is ready (provider hasn't been set
 *  up — should never happen in practice since OnCreate wires it). Throws
 *  on Android if context.startActivity fails (typically a packaging error).
 *  Callers should treat any rejection as "fall back to the JS /call screen". */
export async function startOutgoingCall(params: StartOutgoingCallParams): Promise<boolean> {
  const m = getModule();
  if (!m) throw new Error('Native CallKit module unavailable');
  return await m.startOutgoingCall({
    callee_email: params.calleeEmail,
    callee_name: params.calleeName,
    callee_avatar: params.calleeAvatar,
    caller_name: params.callerName,
    is_video: !!params.isVideo,
    room_name: params.roomName,
    conversation_id: params.conversationId,
    call_id: params.callId,
    lk_url: params.lkUrl,
    lk_token: params.lkToken,
  });
}

/** Launches the full-native group-call screen (Android: GroupCallActivity).
 *  Replaces the RN WebView `/group-call.js` path for native group calls. The
 *  participants array is JSON-stringified into a single intent extra so the
 *  Android side can pre-seed one placeholder tile per invitee before any
 *  LiveKit `ParticipantConnected` events arrive — giving users a "ringing
 *  Maria…" view instead of a blank black screen during the connect phase. */
export async function openGroupCall(params: OpenGroupCallParams): Promise<void> {
  const m = getModule();
  if (!m) throw new Error('Native CallKit module unavailable');
  await m.openGroupCall(
    params.roomName,
    params.lkUrl,
    params.lkToken,
    JSON.stringify(params.participants ?? []),
    params.hasVideo
  );
}

type LkEventName =
  | 'onLkConnected' | 'onLkParticipantConnected' | 'onLkParticipantDisconnected'
  | 'onLkTrackSubscribed' | 'onLkTrackUnsubscribed' | 'onLkConnectionQuality'
  | 'onLkDisconnected' | 'onLkDataReceived' | 'onLkError'
  // __chatyy_native_call_sync 2026-05-19
  | 'onLkLocalAudioChanged' | 'onLkLocalVideoChanged' | 'onLkSpeakerChanged'
  | 'onLkCameraFlipped' | 'onAudioRouteChanged' | 'onCallHoldChanged'
  | 'onPipChanged';

export function onLkEvent<K extends LkEventName>(
  event: K,
  cb: (data: any) => void
): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener(event, cb);
  return () => sub.remove();
}

// ─── RNNoise (2026-05-17) ────────────────────────────────────────────────────
// Per-user ML noise suppression toggle. Defaults to ON. Persistence is owned
// by the native side (SharedPreferences on Android, App Group UserDefaults on
// iOS). JS wrappers swallow failures so a missing native module degrades to
// "always on, no-op" rather than crashing the call screen.

// [#1205 live muting fix, 2026-05-19] Reset audio mode/session BEFORE
// live-broadcast.js calls getUserMedia. Wipes a leaked voice-call audio
// state from a prior call so the live host's mic doesn't get gated to
// near-silence by AEC after ~5s. No-op on platforms where the native
// module isn't loaded (web, etc).
export function prepareAudioForLive(): boolean {
  const m = getNative();
  if (!m) return false;
  try { return !!m.prepareAudioForLive(); } catch { return false; }
}

export function setNoiseSuppression(enabled: boolean): boolean {
  const m = getModule();
  if (!m) return false;
  try { return !!m.setNoiseSuppression(!!enabled); } catch { return false; }
}

export function getNoiseSuppression(): boolean {
  const m = getModule();
  if (!m) return true; // sensible default — match the JS-side mediaTrack constraint
  try { return !!m.getNoiseSuppression(); } catch { return true; }
}

export function isNoiseSuppressionAvailable(): boolean {
  const m = getModule();
  if (!m) return false;
  try { return !!m.isNoiseSuppressionAvailable(); } catch { return false; }
}

// ─── Background blur / virtual background (2026-05-17) ───────────────────────

export type BackgroundMode = 'off' | 'blur_low' | 'blur_medium' | 'blur_high' | 'image';

export function setBackgroundMode(mode: BackgroundMode, imageAsset?: string | null): boolean {
  const m = getModule();
  if (!m) return false;
  try { return !!m.setBackgroundMode(mode, imageAsset ?? null); } catch { return false; }
}

export function getBackgroundMode(): { mode: BackgroundMode; imageAsset: string } {
  const m = getModule();
  const fallback = { mode: 'off' as BackgroundMode, imageAsset: '' };
  if (!m) return fallback;
  try {
    const r = m.getBackgroundMode();
    return { mode: ((r?.mode as BackgroundMode) || 'off'), imageAsset: (r?.imageAsset || '') };
  } catch { return fallback; }
}

export function isBackgroundProcessorAvailable(): boolean {
  const m = getModule();
  if (!m) return false;
  try { return !!m.isBackgroundProcessorAvailable(); } catch { return false; }
}

export function getBackgroundWallpapers(): string[] {
  const m = getModule();
  if (!m) return [];
  try { return Array.isArray(m.getBackgroundWallpapers()) ? m.getBackgroundWallpapers() : []; } catch { return []; }
}

// ─── Screen share (2026-05-17 Stage 4) ───────────────────────────────────────
// Top-level bridge wrapping both platforms' screen-share entry points. On iOS
// this presents the ReplayKit broadcast picker (LiveKit's SampleHandler picks
// up frames inside its extension process); on Android it triggers the
// MediaProjection consent dialog via expo-screen-share. The actual frame
// publish path is owned by LiveKit's LocalParticipant.setScreenShareEnabled.

export async function startScreenshare(audioShare: boolean = false): Promise<boolean> {
  const m = getModule();
  if (!m) return false;
  try { return !!(await m.startScreenshare(!!audioShare)); } catch { return false; }
}

export async function stopScreenshare(): Promise<boolean> {
  const m = getModule();
  if (!m) return false;
  try { return !!(await m.stopScreenshare()); } catch { return false; }
}

// ─── Native CallSignalWs warm-connect (P0 2026-05-18 #1132) ──────────────────
// Opens the native raw WebSocket eagerly so inbound `call_invite` frames
// ring the OS-level CallKit (iOS) / CallRingingService (Android) screen
// even if the JS WS path is broken / paused / lazy-loading. The JS WS
// (services/websocket.js) keeps working in parallel — this is belt-and-
// suspenders against the regression where the callee's app received the
// server frame but never rendered the modal.
export function warmCallSignalWs(): void {
  const m = getModule();
  if (!m) return;
  try { m.warmCallSignalWs(); } catch {}
}

// ─── ShareExtension outbox feedback (iOS, 2026-05-19) ────────────────────
// The native ShareExtension writes successful sends to App Group UserDefaults
// `chatyy.share_outbox` and posts a Darwin notification. AppDelegate
// rebroadcasts it as the `ShareDidSend` NSNotification, ExpoCallKitModule
// forwards to JS via the `onShareDidSend` event. JS reads the queue here,
// dispatches per-conversation chat-list refreshes, then clears the queue.

export function getShareOutbox(): ShareOutboxEntry[] {
  const m = getModule();
  if (!m || typeof m.getShareOutbox !== 'function') return [];
  try { return (m.getShareOutbox() as ShareOutboxEntry[]) || []; } catch { return []; }
}

export function clearShareOutbox(): void {
  const m = getModule();
  if (!m || typeof m.clearShareOutbox !== 'function') return;
  try { m.clearShareOutbox(); } catch {}
}

export function onShareDidSend(
  cb: (data: { entries: ShareOutboxEntry[]; count: number }) => void
): () => void {
  const e = getEmitter();
  if (!e) return () => {};
  const sub = e.addListener('onShareDidSend', cb);
  return () => sub.remove();
}
